print('*'*30 + '\n' +'*'*8 + 'About Triangle' +'*'*8 + '\n' + '*'*30 )
import math
a = float(input('Enter a-side long (cm): '))
b = float(input('Enter b-side long (cm): '))
c = math.sqrt((a**2)+(b**2))
A_ang = math.degrees(math.acos(b/c))
print('A angle is','{:.4f}'.format(A_ang))
B_ang = math.degrees(math.acos(a/c))
print('B angle is','{:.4f}'.format(B_ang))
print('c-side is','{:.4f}'.format(c)+' cm')
print(('*')*30)
